### PR TITLE
Update names of repos for Cloud 6

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by jsuchome** [comment]
Well, originally I thought that creating Cloud6 branch was mistake and we should finally just develop for master now, but since master is ruby only, and Cloud6 admin node still runs only SLE11SP3, I guess it is right to use Cloud6 branch for ycp code until the point when we switch to SLE12 (i.e. ruby-yast capable) admin nodes.

**Comment by jsuchome** [comment]
Please add a changelog entry and bump the version to 2.17.44 (so we do not conflict with Cloud5 ones)

**Comment by vuntz** [comment]
@jsuchome done. Shouldn't we bump to something higher than 2.17.44 in case Cloud 5 get more updates for this module?

**Comment by jsuchome** [comment]
If Cloud5 needs updates, that it will get 2.17.43.X versions.

And this is temporary anyway, as once we switch to SLE12 completely, we will jump to 3.X.Y versioning.

**Pull request merged**
